### ISSUE TITLE
Prompt Travel not working

### ISSUE THREAD

**Issue by Lumoria** [continue-revolution/sd-webui-animatediff#193]
What steps need to be done to get this working? I have Auto1111 1.6, ControlNet v1.1.410, Deforum 3.0. I also tried reinstalling this extension just in case.

I run this prompt: 
house
0: blue
8: red

Command line says that were using prompt travel but the results show a blue house, no red halfway though the animation. Prompt travel seems to only be reading the prompt on frame 0. What am I missing here?

**Comment by continue-revolution** [comment]
https://github.com/continue-revolution/sd-webui-animatediff/blob/master/scripts/animatediff_prompt.py#L97 

add `assert not torch.equal(cond_list[0], cond_list[8]), "they should not be equal"` above this line. The indentation should be the same. also add print("interpolation running") above this assertion to make sure that you are really running this interpolation.

If things goes ok then the assertion should not be triggered but you should see "interpolation running" in your terminal

remember to remove these after test to receive future updates.

**Comment by Lumoria** [comment]
Should it look like this? 

        for i in range(cond.shape[0]):
            cond_list.append(self.single_cond(i, cond.shape[0], cond))
        print("interpolation running")
        assert not torch.equal(cond_list[0], cond_list[8]), "they should not be equal"
        return torch.stack(cond_list).to(cond.dtype).to(cond.device)

Running with this crashes with "AssertionError: they should not be equal"

**Comment by continue-revolution** [comment]
Yes. Remove those added lines and add the following at https://github.com/continue-revolution/sd-webui-animatediff/blob/master/scripts/animatediff_prompt.py#L75 indentation should be the same as L76

logger.info(f'center_frame: {center_frame}, key_prev: {key_prev}, key_next: {key_next}')

**Comment by Lumoria** [comment]
Here's the log (idk how to properly paste long logs here)
[log.txt](https://github.com/continue-revolution/sd-webui-animatediff/files/12851070/log.txt)

**Comment by continue-revolution** [comment]
I don't understand. These all seem to be normal. Then do two things all together at once

add print(p.prompt) after https://github.com/continue-revolution/sd-webui-animatediff/blob/master/scripts/animatediff_prompt.py#L61 indentation same as L61

replace `assert not torch.equal(cond_list[0], cond_list[8]), "they should not be equal"` you added previously with `assert not torch.equal(cond[0], cond[8]), "they should not be equal"`

**Comment by Lumoria** [comment]
Same crash as before, but with "AssertionError: they should not be equal"

**Comment by continue-revolution** [comment]
> add print(p.prompt) after https://github.com/continue-revolution/sd-webui-animatediff/blob/master/scripts/animatediff_prompt.py#L61 indentation same as L61

What is p.prompt?

**Comment by Lumoria** [comment]
Sorry, was about to edit that in, it is this ['house, blue house, ', 'house, blue house, ', 'house, blue house, ', 'house, blue house, ', 'house, blue house, ', 'house, blue house, ', 'house, blue house, ', 'house, blue house, ', 'house, fire, ', 'house, fire, ', 'house, fire, ', 'house, fire, ', 'house, fire, ', 'house, fire, ', 'house, fire, ', 'house, fire, ']

**Comment by continue-revolution** [comment]
I honestly don't understand. Your clip text encoder seems to refuse encoding "house, fire, " due to some unknown reason. Similar prompt syntax on my side will not cause any assersion error.

Maybe some extension manipulated the logic of prompt encoding, but I don't know which. My extension combination looks like this: https://user-images.githubusercontent.com/63914308/273689420-fa3ae0f8-af22-4f20-93c7-2f17f622b452.png

**Comment by Seryogerr** [comment]
Hi, it doesn't work for me too)
Trying change animatediff_prompt.py but the plugin disappeared from the ui))
I noticed in png info,that image dont have prompt after 0: "prompt", 

ofc in console "AnimateDiff - INFO - You are using prompt travel"

![2023-10-10_02-14-14](https://github.com/continue-revolution/sd-webui-animatediff/assets/147452692/dae1e62b-b8e8-424b-9945-787e68df5a43)
![image](https://github.com/continue-revolution/sd-webui-animatediff/assets/147452692/55c12d32-dce7-4757-a09f-3702d9ad6129)

**Comment by Lumoria** [comment]
I'm installing a clean copy of Auto1111, I'll see if there is some extension interference here. Thanks for the help so far!

**Comment by continue-revolution** [comment]
you can always add that assertion error (whichever is ok) to that place. When it disappears, it means that you are good to go.

**Comment by Seryogerr** [comment]
If I understand correctly from other topics, a prerequisite for working prompt travel, are these checkboxes necessary in the controller settings?
Yes i put it on but nothing changes
Maybe we have a difference in the models or the controlnet yaml files?
![2023-10-10_02-20-40](https://github.com/continue-revolution/sd-webui-animatediff/assets/147452692/2861df58-e77a-4285-95c4-35801c0fbb98)

**Comment by Seryogerr** [comment]
and the last guess
maybe we have different COMMANDLINE_ARGS= ?
For example, I have set COMMANDLINE_ARGS=--medvram --xformers --api --autolaunch

**Comment by continue-revolution** [comment]
It has nothing to do with ControlNet settings. ControlNet function `processing_process_images_hijack` will always hook a function `process_image_inner` in A1111, and I hooked `processing_process_images_hijack` inside my own extension. That's where prompt parsing happens.

**Comment by continue-revolution** [comment]
It seems to me that nothing wrong happed inside my extension. Most likely something outside my extension manipulated the logic of A1111.

**Comment by Seryogerr** [comment]
In the correct work of prompt travel, do you see different prompts in png info?

**Comment by continue-revolution** [comment]
It's normal to see different prompts in png info.

**Comment by Lumoria** [comment]
Ok so I disabled all extensions besides AnimateDiff, controlnet and Deforum. The assertion error no longer gets tripped, so that part was some extension interference. Now my problem still is that the animation doesn't seem to be following the keyframes. I used this prompt:

0: girl
8: forest

[', girl, ', ', girl, ', ', girl, ', ', girl, ', ', girl, ', ', girl, ', ', girl, ', ', girl, ', ', forest, ', ', forest, ', ', forest, ', ', forest, ', ', forest, ', ', forest, ', ', forest, ', ', forest, ']


This outputs an animation of a girl walking through a forest, but the forest is already there from frame 0.

**Comment by continue-revolution** [comment]
Not really. This prompt seems like a girl gradually becomes a forest.

**Comment by continue-revolution** [comment]
It's normal that forest appear in frame 1 because of prompt interpolation. Then AnimateDiff motion module will affect frame 0 so the forest appears at frame 0. I don't think you can use prompt travel in this way.

**Comment by Lumoria** [comment]
Gotcha, I just need to learn how to prompt this better then. I used this prompt I saw on twitter:

0: (serious face:0.5),( looking away:1.2), 
3: open eyes, looking at viewer, 
4: (closed eyes:1.2)
5: open eyes
6: (smile:0.8)

The outputs match the result that was on twitter. Everything seems to be working fine now. Thank you so much for helping me with this! 
![00057-3823656607](https://github.com/continue-revolution/sd-webui-animatediff/assets/12161172/0ca5fd2b-5066-4ca0-989c-69923e8d0d36)

**Comment by continue-revolution** [comment]
@Lumoria can you post the extension list you have installed? I will guess which one affected my extension when I have time.

**Comment by Seryogerr** [comment]
lol get ready, it's going to be fun
I decided to check on my automatic runpod...
Everything works well there, but there is an old controlnet v1.1.313 that gives an error in the log)

2023-10-10T00:08:20.795896435Z *** Error running postprocess_batch: /workspace/stable-diffusion-webui/extensions/sd-webui-controlnet/scripts/controlnet.py
2023-10-10T00:08:20.795919032Z     Traceback (most recent call last):
2023-10-10T00:08:20.795922136Z       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 659, in postprocess_batch
2023-10-10T00:08:20.795924576Z         script.postprocess_batch(p, *script_args, images=images, **kwargs)
2023-10-10T00:08:20.795926755Z     TypeError: 'NoneType' object is not callable

And this 

2023-10-10T00:07:26.310389044Z *** Error running before_process: /workspace/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py
2023-10-10T00:07:26.310505574Z     Traceback (most recent call last):
2023-10-10T00:07:26.310509652Z       File "/workspace/stable-diffusion-webui/modules/scripts.py", line 611, in before_process
2023-10-10T00:07:26.310511752Z         script.before_process(p, *script_args)
2023-10-10T00:07:26.310513784Z       File "/workspace/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff.py", line 56, in before_process
2023-10-10T00:07:26.310516326Z         self.cn_hacker.hack(params)
2023-10-10T00:07:26.310519336Z       File "/workspace/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_cn.py", line 611, in hack
2023-10-10T00:07:26.310521855Z         self.hack_cn()
2023-10-10T00:07:26.310524135Z       File "/workspace/stable-diffusion-webui/extensions/sd-webui-animatediff/scripts/animatediff_cn.py", line 136, in hack_cn
2023-10-10T00:07:26.310526281Z         from scripts.controlmodel_ipadapter import (PlugableIPAdapter,
2023-10-10T00:07:26.310528290Z     ModuleNotFoundError: No module named 'scripts.controlmodel_ipadapter'


BUT everything works well)))

a girl, 
0: in forest
8: in city
16: in car
24: in space
![00030-788859703](https://github.com/continue-revolution/sd-webui-animatediff/assets/147452692/62aa0a9f-25cc-4f04-90f8-dbe1eb061816)

the difference between automatics:

Gray=Runpod 
![2023-10-10_03-12-38](https://github.com/continue-revolution/sd-webui-animatediff/assets/147452692/e9e6e993-fa5d-4b6e-a563-1892308c67c1)


Black=Local
![2023-10-10_03-12-27](https://github.com/continue-revolution/sd-webui-animatediff/assets/147452692/db9d7028-f67a-4707-af50-f10799e42621)


**When i make screenshots i noticed that i have old xformers: 0.0.20 on my local version)))**

I hope everything will work after the update) because the same prompt does not work on the local version

**Comment by Lumoria** [comment]
> @Lumoria can you post the extension list you have installed? I will guess which one affected my extension when I have time.

I will now work on enabling my extensions one at a time. I'll let you know which one breaks this.

**Comment by continue-revolution** [comment]
@Seryogerr Do not update your xformers to 0.0.21. I updated and reverted back because it won't allow me to input a large tensor

**Comment by Seryogerr** [comment]
> @Seryogerr Do not update your xformers to 0.0.21. I updated and reverted back because it won't allow me to input a large tensor
> 
> But if xformers 0.0.21 works then it will be fine. It's just not working on my machine.

I'm a little afraid to update xformers, but the difference between automatics is xformers and python: 3.10.6 vs python: 3.10.12 

plus runpod have old deforum and contolnet,but I don't think it's good))

**Comment by Lumoria** [comment]
@continue-revolution Ok so when I have DynamicPrompts enabled, this doesn't crash, but it does make the animation veer far off of the expected results. This is a real bummer because I use this extension heavily.

**Comment by continue-revolution** [comment]
https://github.com/adieyal/sd-dynamic-prompts/blob/main/sd_dynamic_prompts/dynamic_prompting.py#L532

This is the reason why you should not use dynamic prompt with animatediff prompt travel. It change p.prompt AFTER I change it.

**Comment by neversay** [comment]
The same here, when I tried the prompt travel with DynamicPrompt on, I can see a INFO log on my console:
INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 16 images in a total of 1 batches.
And it make the rendered images not obey the prompt travel.

**Comment by continue-revolution** [comment]
@Lumoria When some extension made that assertion error happen, please let me know which.

**Comment by continue-revolution** [comment]
Another problem with dynamic prompt is that - it will change prompts for EVERY frame, instead of a smooth curved interpolation, which will harm animatediff generation.

**Comment by Seryogerr** [comment]
> The same here, when I tried the prompt travel with DynamicPrompt on, I can see a INFO log on my console: INFO:sd_dynamic_prompts.dynamic_prompting:Prompt matrix will create 16 images in a total of 1 batches. And it make the rendered images not obey the prompt travel.

Holly, same log with DP :D
but I didn't attach any importance to it)
I thought it was another Hack like Hacking ControlNet :D

**Comment by Lumoria** [comment]
> @Lumoria When some extension made that assertion error happen, please let me know which.

Sorry, no luck in getting this error to happen again (I guess this is a good thing? lol) After re-adding my extensions one by one, the assertion error no longer happens. Here is all of my extensions if you wanted to try to figure this out:
![Screenshot_20231009_205046](https://github.com/continue-revolution/sd-webui-animatediff/assets/12161172/3737fbd7-2053-46db-a2f7-9e44fa1f2824)

**Comment by TianbingFromChina** [comment]
I can't get prompt travel work.
