### ISSUE TITLE
[Feature]: Stable Video Diffusion from SAI

### ISSUE THREAD

**Issue by uk9921** [continue-revolution/sd-webui-animatediff#339]
### Expected behavior

stable-diffusion released [img2video](https://github.com/Stability-AI/generative-models) model. Do you have plan to support it?

**Comment by continue-revolution** [comment]
I've already noticed this model. I do have plan to support it in some way. Please wait patiently.

**Comment by drhead** [comment]
I have actually tested using the special VAE decoder from the SVD model with AnimateDiff outputs and it helps output quality quite a bit, removing a lot of noise.  That could be implemented *relatively* easily and bring a great benefit.

**Comment by continue-revolution** [comment]
Interesting. @drhead Do you mean replacing the original VAE with SVD VAE?

**Comment by uk9921** [comment]
@drhead Can you elaborate more on this? Do you input the latents generated by Animatediff into the VAE decoder of SVD?

**Comment by drhead** [comment]
> Interesting. @drhead Do you mean replacing the original VAE with SVD VAE?

Latents output from AnimateDiff can be decoded using the decoder half of the SVD VAE.  They are then decoded with temporal awareness, which eliminates a large amount of noise in the output.  I have only been able to do a modest amount of testing and have only tested it on realistic-style videos (since lack of training data may mean there will be issues decoding animation-style videos), but from what I can tell so far it does work rather well.  Main issue is porting the model out of the SGM codebase.

**Comment by continue-revolution** [comment]
@drhead it would be helpful if you could share some code with me

**Comment by uk9921** [comment]
@drhead Very reasonable. We are very much looking forward to you sharing some examples of the differences before and after using SVD-VAE.

**Comment by zhangrc** [comment]
Is my 3060 still sufficient? Is it necessary to upgrade the GPU

**Comment by andzejsp** [comment]
when? world is waiting

**Comment by uk9921** [comment]
@zhangrc It depends on your img size
ref to this:  https://github.com/Stability-AI/generative-models/issues/140#issuecomment-1822161388

**Comment by uk9921** [comment]
f5 is broken

**Comment by continue-revolution** [comment]
this is now available via Forge. Unfortunately it is too hard if we want it on OG A1111.
