### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by bryansmosh** [continue-revolution/sd-webui-animatediff#36]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

Just reporting bugs I found, Love your work, keep going!

1. Character limit bug, if you use a mid size + prompt, itll generate two different images, and they won't move much either

2. Using the seed of a static generated photo, does not translate to the same seed being used when the extension is enabled. They are very different images, almost like the seed is useless.

3.the muted colors, but I think you're fixing that

thank you! <3

### Steps to reproduce the problem

1. make a decent sized prompt, like with atleast 25 words
2. try replicating an image in animateDiff with a static generation
3. 

### What should have happened?

shouldve worked

### Commit where the problem happens

webui: 
extension: 

### Command Line Arguments

```Shell
idk
```

### Console logs

```Shell
idk
```

**Comment by continue-revolution** [comment]
> Character limit bug, if you use a mid size + prompt, itll generate two different images, and they won't move much either

Yes, this [prompt issue](https://github.com/continue-revolution/sd-webui-animatediff/issues/4) have been addressed before. I don't have time to resolve it at this time, but will resolve it later when some more-urgent issue have been fixed.

Please track the progress of this issue in #4 

> Using the seed of a static generated photo, does not translate to the same seed being used when the extension is enabled. They are very different images, almost like the seed is useless.

Unfortunately, this is expected. This is due to their motion module. The latent has been completely changed. I am not able to do much about that.

Will close this issue at this time.

**Comment by antispamtutoruser123** [comment]
This character limit issue is the #1 issue for me right now.  I used to think the blurriness problem was #1 but the bluriness problem only effects about 30% of runs.  The character limit issue effects about 80-90%
