### ISSUE TITLE
[Bug]:  run animatediff stop  reload stable diffusion

### ISSUE THREAD

**Issue by rookiexjl** [continue-revolution/sd-webui-animatediff#61]
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits of both this extension and the webui

### Have you read FAQ on README?

- [X] I have updated WebUI and this extension to the latest version

### What happened?

[Bug]:  run animatediff stop  reload stable diffusion

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...
[Bug]:  run animatediff stop  reload stable diffusion

### What should have happened?

[Bug]:  run animatediff stop  reload stable diffusion

### Commit where the problem happens

webui: 
extension: 
[Bug]:  run animatediff stop  reload stable diffusion

### Command Line Arguments

```Shell
[Bug]:  run animatediff stop  reload stable diffusion
```

### Console logs

```Shell
[Bug]:  run animatediff stop  reload stable diffusion
```

### Additional information

[Bug]:  run animatediff stop  reload stable diffusion

**Comment by rookiexjl** [comment]
什么事

**Comment by jlitz** [comment]
was this issue solved?  i am running animatediff on comfy and it continue to reload clone models  739 seconds to create gif    


To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
install: ['https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git']
Download: git clone 'https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git'
[!]
0it [00:00, ?it/s]Cmd('git') failed due to: exit code(128)
   cmdline: git clone -v --recursive --progress -- https://github.com/ssitu/ComfyUI_UltimateSDUpscale.git C:\COMFY\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
0it [00:00, ?it/s]got prompt
model_type EPS
adm 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
left over keys: dict_keys(['model_ema.decay', 'model_ema.num_updates', 'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
loaded straight to GPU
Requested to load BaseModel
Loading 1 new model
[AnimateDiffEvo] - INFO - Loading motion module animatediffMotion_v15V2.ckpt
[AnimateDiffEvo] - INFO - Using fp16, converting motion module to fp16
Requested to load SD1ClipModel
Loading 1 new model
[AnimateDiffEvo] - INFO - Sliding context window activated - latents passed in (50) greater than context_length 16.
[AnimateDiffEvo] - INFO - Injecting motion module animatediffMotion_v15V2.ckpt version v2.
Requested to load BaseModel
Loading 1 new model
unload clone 1
100%|██████████████████████████████████████████████████████████████████████████████████| 25/25 [11:26<00:00, 27.46s/it]
[AnimateDiffEvo] - INFO - Ejecting motion module animatediffMotion_v15V2.ckpt version v2.
[AnimateDiffEvo] - INFO - Cleaning motion module from unet.
[AnimateDiffEvo] - INFO - Removing motion module animatediffMotion_v15V2.ckpt from cache
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
Leftover VAE keys ['model_ema.decay', 'model_ema.num_updates']
Prompt executed in 739.25 seconds

**Comment by continue-revolution** [comment]
anything related to comfy should be posted to comfy repo, not here.

**Comment by jlitz** [comment]
TNX FOR THE HELP
